# FROM python:3.11.4

# WORKDIR /myapp

# COPY requirements.txt /myapp/

# RUN pip install -r requirements.txt

# COPY . /myapp/
# EXPOSE 8000

# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
