# Generated by Django 4.2.4 on 2023-09-12 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
